version: "3"

services:
  postgres:
    image: postgres:11.4
    container_name: shymbo
    ports:
      - "5435:5432"
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=POST123
      - POSTGRES_DB=nestJSshymbo
    restart: always
