version: "3"

services:
  postgres:
    image: postgres:11.4
    container_name: mobiko_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=devjetzt
    restart: always
