import { Entity, PrimaryGeneratedColumn, Column, Timestamp, ManyToOne, ManyToMany, JoinTable, CreateDateColumn, UpdateDateColumn, OneToMany } from 'typeorm';

import { ListDto } from '../list/list.dto';
import { UserDto } from '../user/user.dto';
import { UserEntity } from '../user//user.entity';
import { ItemEntity } from '../item//item.entity';
import { GroupEntity } from '../group/group.entity';

@Entity()
export class ListEntity {

    @PrimaryGeneratedColumn('uuid')
    public id: string;

    @Column('boolean', {default: false})
    public public: boolean;

    @Column()
    public title: string;

    @Column()
    public description: string;


    //Relations
    @ManyToOne(type => UserEntity, user => user.id)
    owner: UserEntity; 


    // Autogenerated
    @CreateDateColumn({update: false})
    public created: Date;

    @UpdateDateColumn()
    public updated: Date;
 

    public static createFromDto(dto: ListDto): ListEntity {
        const entity = new ListEntity();
        entity.id = dto.id;
        entity.public = dto.public;
        entity.title = dto.title;
        entity.description = dto.description;
        return entity;
    }

}